# Site settings
title: Synthetic Health Data Hub
description: >-
  The definitive resource hub for tabular synthetic health data, 
  covering algorithms, tools, regulations, and community resources.
baseurl: "/synthetic-health-data-hub" # the subpath of your site, e.g. /blog
url: "https://digitalhealthcrclimited.github.io" # the base hostname & protocol for your site

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-remote-theme

# Theme configuration
show_downloads: false
google_analytics:

# Collections for different content types
collections:
  technical:
    output: true
    permalink: /technical/:path/
    sort_by: title
  ecosystem:
    output: true
    permalink: /ecosystem/:path/
    sort_by: title
  regulatory:
    output: true
    permalink: /regulatory/:path/
    sort_by: region
  community:
    output: true
    permalink: /community/:path/
    sort_by: name
  education:
    output: true
    permalink: /education/:path/
    sort_by: date
  use_cases:
    output: true
    permalink: /use-cases/:path/
    sort_by: date
  privacy_security:
    output: true
    permalink: /privacy-security/:path/
    sort_by: priority
  benchmarks:
    output: true
    permalink: /benchmarks/:path/
    sort_by: title

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: "technical"
    values:
      nav_order: 1
      parent: "Technical Resources"
  - scope:
      path: ""
      type: "ecosystem"
    values:
      nav_order: 2
      parent: "Software Ecosystem"
  - scope:
      path: ""
      type: "regulatory"
    values:
      nav_order: 3
      parent: "Regulatory & Compliance"
  - scope:
      path: ""
      type: "community"
    values:
      nav_order: 4
      parent: "Community"
  - scope:
      path: ""
      type: "education"
    values:
      nav_order: 5
      parent: "Education"
  - scope:
      path: ""
      type: "use_cases"
    values:
      nav_order: 6
      parent: "Use Cases"
  - scope:
      path: ""
      type: "privacy_security"
    values:
      nav_order: 7
      parent: "Privacy & Security"
  - scope:
      path: ""
      type: "benchmarks"
    values:
      nav_order: 8
      parent: "Benchmarks"

# Footer content
footer_content: "Copyright &copy; 2024 Synthetic Health Data Hub. Distributed under <a href=\"https://github.com/your-repo/blob/main/LICENSE\">MIT license</a>."


# Google Analytics (optional)
# ga_tracking: UA-XXXXXXXXX-X



# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - webpack.config.js
  - README.md
  - CONTRIBUTING.md
  - LICENSE